
rundiaWaitCheck= "var status = document.querySelectorAll('speed-test div  pv-button  button')[0].disabled;return status;"
speedTestTableData="var detaildict = {}; var datacount = document.querySelectorAll('tbody')[0].childElementCount; var j = 1; for (var i = 0; i < datacount; i++) {time = document.querySelectorAll('speed-test-history tbody > tr:nth-child(' + j + ') > td:nth-child(1)')[0].innerText.trim();event = document.querySelectorAll('speed-test-history tbody > tr:nth-child(' + j + ') > td:nth-child(2)')[0].innerText.trim();desc = document.querySelectorAll('speed-test-history tbody > tr:nth-child(' + j + ') > td:nth-child(3)')[0].innerText.trim();ping=document.querySelectorAll('speed-test-history tbody > tr:nth-child(' + j + ') > td:nth-child(4)')[0].innerText.trim();jitter=document.querySelectorAll('speed-test-history tbody > tr:nth-child(' + j + ') > td:nth-child(5)')[0].innerText.trim();serverName=document.querySelectorAll('speed-test-history tbody > tr:nth-child(' + j + ') > td:nth-child(6')[0].innerText.trim();speedTestMode= document.querySelectorAll('speed-test-history tbody > tr:nth-child(' + j + ') > td:nth-child(7)')[0].innerText.trim();detaildict[i] = {'Date': time, 'Download': event,'Upload': desc, 'Ping':ping,'Jitter':jitter,'Server':serverName,'Mode':speedTestMode}; j++; } return detaildict;"
containerApplicationInstalled="var appList = {};var rows = document.querySelectorAll('div[class=\"installed-applications pv-yscroll-div\"] table tbody')[0].childElementCount; for(var i=1;i<=rows;i++){var appDatasubDict = {};appDatasubDict['TableRow']=i;appDatasubDict['Name']= document.querySelectorAll(\"div[class='installed-applications pv-yscroll-div'] table tbody tr:nth-child(\"+ i + \") td:nth-child(1)\")[0].innerText;appDatasubDict['Version']= document.querySelectorAll(\"div[class='installed-applications pv-yscroll-div'] table tbody tr:nth-child(\"+ i + \") td:nth-child(2)\")[0].innerText;appDatasubDict['Running']=document.querySelectorAll(\"div[class='installed-applications pv-yscroll-div'] table tbody tr:nth-child(\"+ i + \") td:nth-child(3) pv-toggle[id='running'] input\")[0].checked;appDatasubDict['Autostart']= document.querySelectorAll(\"div[class='installed-applications pv-yscroll-div'] table tbody tr:nth-child(\"+ i + \") td:nth-child(4) pv-toggle[id='running'] input\")[0].checked;appDatasubDict['Remove']= document.querySelectorAll(\"div[class='installed-applications pv-yscroll-div'] table tbody tr:nth-child(\"+ i + \") td:nth-child(5) pv-button\")[0].className;appList[appDatasubDict['Name']]= appDatasubDict;}return appList;"
closeToaster="document.querySelectorAll('#toast-container button span')[0].click();"
customerInfoJavaScript="var info=document.querySelectorAll(\"CUSTOMERINFOLOCATOR\")[0].innerText.trim();return info;"
#GetSSIDDataPortal="count=document.querySelectorAll('ghz-settings[ghztype=INDEX] pv-card > div > div.pv-card__body > form > ul:nth-child(1)')[0].childElementCount; \ ssidList={}; \ for (var i = 1; i < count; i++){ \    data = document.querySelectorAll('ghz-settings[ghztype=INDEX] pv-card > div > div.pv-card__body > form > ul:nth-child(1)')[0].children[i].innerText; \ \    data1=data.split('\\n'); \    ssidList[data1[0]]=data1[1]; }; return ssidList;"
GetSSIDDataPortal="count=document.querySelectorAll('ghz-settings[ghztype=INDEX] pv-card > div > div.pv-card__body > form > ul:nth-child(1)')[0].childElementCount; ssidList={};  for (var i = 1; i < count; i++){ data = document.querySelectorAll('ghz-settings[ghztype=INDEX] pv-card > div > div.pv-card__body > form > ul:nth-child(1)')[0].children[i].innerText;  data1=data.split('\\n');   ssidList[data1[0]]=data1[1]; }; return ssidList;"
PingTestTableData="var detaildict = {}; Minval = document.querySelectorAll('ping-test-history:nth-child(1) > div:nth-child(1) > pv-data-table:nth-child(2) > div:nth-child(1) > p-table:nth-child(1) > div:nth-child(1) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2)')[0].innerText.trim(); Maxval = document.querySelectorAll('ping-test-history:nth-child(1) > div:nth-child(1) > pv-data-table:nth-child(2) > div:nth-child(1) > p-table:nth-child(1) > div:nth-child(1) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(3)')[0].innerText.trim(); Avgval = document.querySelectorAll('ping-test-history:nth-child(1) > div:nth-child(1) > pv-data-table:nth-child(2) > div:nth-child(1) > p-table:nth-child(1) > div:nth-child(1) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(4)')[0].innerText.trim(); Server = document.querySelectorAll('ping-test-history:nth-child(1) > div:nth-child(1) > pv-data-table:nth-child(2) > div:nth-child(1) > p-table:nth-child(1) > div:nth-child(1) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(5)')[0].innerText.trim(); detaildict = {'Minimum ms': Minval, 'Maximum ms': Maxval,'Average ms': Avgval, 'Server':Server}; return detaildict;"
PingTestTableData1="count=document.querySelectorAll('ping-test-history:nth-child(1) > div:nth-child(1) > pv-data-table:nth-child(2) > div:nth-child(1) > p-table:nth-child(1) > div:nth-child(1) > div:nth-child(1) > table:nth-child(1) > tbody:nth-child(2)')[0].childElementCount; return count;"
PingCustomerPagePagination="text=document.querySelectorAll(SELECTOR)[0].innerText; return text;"
PingCustomerPagePaginationArrow="status=document.querySelectorAll(SELECTOR)[INDEX].disabled; return status;"

#DatamodelBrowser
DataModelRadioButtonCheck="status=document.querySelectorAll('div:nth-child(1) > div.list-item-title.flex-row > p-radiobutton > div > div.p-hidden-accessible > input[type=radio]')[0].checked;return status;"
DataModelEditableCheck="value=document.querySelectorAll('app-usp-browser-data > pv-card > div > div.pv-card__body > div > div > div.all-dms.ng-star-inserted > div.data-model-list.pv-yscroll-div > div > div.list-item-info.flex.ng-star-inserted > div:nth-child(4) > pv-input')[0].getAttributeNames(); return value;"
DataModelEditableCheck1="value=document.querySelectorAll('app-usp-browser-data > pv-card > div > div.pv-card__body > div > div > div.all-dms.ng-star-inserted > div.data-model-list.pv-yscroll-div > div > div.list-item-info.flex.ng-star-inserted > div.model-info.flex-row.ng-star-inserted > pv-input')[0].getAttributeNames(); return value;"
#Network History
NetworkHistorytabcount="count=document.querySelectorAll('#historytabviewID > div > div.p-tabview-nav-container > div > ul')[0].childElementCount; return count;"
NetworkHistoryDeviceList="TextList=document.querySelectorAll('.p-multiselect-panel.p-component.ng-star-inserted')[0].innerText; return TextList;"
EventHistoryPagePagination="text=document.querySelectorAll(SELECTOR)[0].innerText; return text;"
EventHistoryPagePaginationArrow="status=document.querySelectorAll(SELECTOR)[INDEX].disabled; return status;"
EventHistoryTable="NHEventList = []; var rowcount = document.querySelectorAll('app-network-history > div.history-data-container > pv-card > div > div.pv-card__body > pv-data-table > div > p-table > div.pv-table__table > div.p-datatable-wrapper > table > tbody')[0].childElementCount; var j = 2; for (var i = 1; i < rowcount; i++) {Event = document.querySelectorAll('app-network-history > div.history-data-container > pv-card > div > div.pv-card__body > pv-data-table > div > p-table > div.pv-table__table > div.p-datatable-wrapper > table > tbody > tr:nth-child(' + i + ') > td:nth-child(' + j + ')')[0].innerText.trim(); NHEventList.push(Event) ; } return NHEventList;"
EnableCalendardatetimeEdit="document.querySelectorAll('app-network-history')[0].removeAttribute('readonly')"
EditCalendardatetime="document.querySelectorAll('app-network-history > div.search-container > div > input[type=text]')[0].value ='SELECTOR'"
EditCalendardatetimeemptyvalue="document.querySelectorAll('app-network-history > div.search-container > div > input[type=text]')[0].value ='"
EventHistoryCalendar="document.querySelectorAll('app-network-history > div.search-container > div > input[type=text]')[0].click()"
EventCalendarApply="document.querySelectorAll('body > div.daterangepicker.ltr.show-calendar.opensright > div.drp-buttons > button.applyBtn.btn.btn-sm.btn-primary')[0].click()"

#Remotelogging
Get_displayed_output="var textAreaOutput = document.querySelector('textarea').value; return textAreaOutput"
Get_text_of_input="""var textInput = document.querySelector("input[placeholder='Enter the commands']").value; return textInput"""

campaignToggle="status=document.querySelectorAll(\"SELECTOR\")[0].checked;return status;"

networkTabLog="status=JSON.parse(JSON.stringify(window.performance.getEntries()));return status;"
expandSideBar="document.querySelectorAll('app-whw-header > nav > div.logo.flex-row.flex-row__start-center > pv-vector')[0].click()"
#deviceList= "var devicePageConnectedDeviceTableData = Array.from(document.querySelectorAll('.device-list-page .p-datatable-tbody tr'));var count = devicePageConnectedDeviceTableData.length;let devicesMacList = [];for(let i=0;i<count;i++){devicesMacList.push(devicePageConnectedDeviceTableData[i].innerText.split('  ')[1]);} return devicesMacList"
deviceList= 'devicePageConnectedDeviceTableData = Array.from(document.querySelectorAll(".device-list-page .p-datatable-tbody tr"));var count = devicePageConnectedDeviceTableData.length;let devicesMacList = [];for(let i=0;i<count;i++){devicesMacList.push(devicePageConnectedDeviceTableData[i].innerText.split("  ")[1]);}; return devicesMacList'
eleDeviceDetailCalendar="//div[@id='rssi-filter']//input[@name='datetimes']"
DeviceDetailCalAttribute = "document.querySelectorAll('#rssi-filter > input[type=text]')[0].removeAttribute('readonly')"
EditDeviceDetailCal = "document.querySelectorAll('#rssi-filter > input[type=text]')[0].value ='SELECTOR'"
RoamingHistory="return (function() { var circleValues1 = [];    var circleElements = document.querySelectorAll('svg > circle');    for (var i = 0; i < circleElements.length; i++) {        var point = circleElements[i].className.baseVal.includes('vis-point');        if (point === true) {            var circleData = circleElements[i].nextElementSibling.innerHTML;        var circleTextData = circleData.split(';');     var circleTextDataInfo = {};            for (var j = 0; j < circleTextData.length; j++) {                if (circleTextData[j] === '') {                    break;                }                var circleTextData1 = circleTextData[j].split(':');                if (circleTextData1.length > 1) {                    circleTextData1[0] = circleTextData1[0].trim();                    circleTextData1[1] = circleTextData1[1].trim();                    circleTextDataInfo[circleTextData1[0]] = circleTextData1[1];                }            }            circleValues1.push(circleTextDataInfo);        }    }    return circleValues1;}) ()"
#wifi Optimization
groupModelDelete="document.querySelectorAll('app-groups-model pv-vector[name=\"circle_delete\"]')[0].click()"

TopologyAssociatedDevices="count=document.querySelectorAll('#home-network-assiocated-devices > div > div.pv-card__body > div > table > tbody')[0].childElementCount;return count;"
