eleCortecaMarketPlace="xpath=//div[contains(text(),'Marketplace')]"
eleCortecaMarketPlaceAllApps="xpath=//section[@class='all-apps']"
eleCortecaMarketPlaceAppSelect="xpath=//div//marketplace-app[contains(.,'APPSELECT')]"
eleCortecaMarketPlaceAppPurchaseStatus="xpath=//div//marketplace-app[contains(.,'APPSELECT')]//div[@class='marketplace-app__right']"
eleCortecaMarketPlaceAppDetailsPage="css=#app-details"
eleCortecaMarketPlaceAppDetailsGet="xpath=//pv-button[contains(.,'Get')]"
eleCortecaMarketPlaceAppDetailsAgree="xpath=//button[contains(.,'Agree')]"
eleCortecaMarketPlaceAppDetailsSuccess="xpath=//div[contains(@class,'app-success')]"
eleCortecaMarketPlaceAppDetailsAvailableApp="xpath=//button[contains(.,' Available application')]"
eleCortecaMarketPlaceAppDetailsStatus="xpath=//div[contains(@class,'app-details__header-get')]"
eleCortecaMarketPlaceAppDetailsContactSales="xpath=//button[contains(.,'Contact sales')]"

#gmail verification
eleEmailInput="css=#identifierId"
eleNextBtn="css=#identifierNext  button"
eleEmailPaswd="css=#password input"
elePaswdNextBtn="css=#passwordNext button"
eleEmailBodyClick="xpath=//div[@role='tabpanel']//tr[contains(.,'SUBJECT')]"
eleEmailBody="xpath=div.adn.ads"
