Kibanasecondusrnamein='xpath=//*[name()=\'input\' and @type="text" and @placeholder="Username"] '
Kibanasecondpasswrdin='xpath=//*[name()=\'input\' and @type="password" and @placeholder="Password"] '
Kibanasecondsignin='xpath=//*[name()=\'button\' and @type="submit"]'
KibanaWelcomePage='xpath=//footer/button[2]/span/span'
Kibanatenantgobal='xpath=//*[name()=\'label\' and @class="euiRadio__label" and @for="global" ]'
Kibanatenantconfirm='xpath=//*[name()=\'button\' and @data-test-subj="confirm"]'
Kibanadiscover='xpath=app/kibana#/discover'
Kibanaplatformsidebar='xpath=//*[name()=\'button\' and @data-test-subj="indexPattern-switch-link"]'
Kibanaplatformselect='xpath=//*[name()=\'input\' and @type="search" and @placeholder="Filter options"]'
# Kibanaplatformclick='xpath=//*[name()=\'span\' and @class="euiSelectableListItem__text"]'
Kibanaplatformclick='xpath=//li[@title="PLATFORM"]//span[@class="euiSelectableListItem__text"]'
Kibanadatepicker='xpath=//*[name()=\'button\' and @data-test-subj="superDatePickerToggleQuickMenuButton"]'
Kibanatimepicker='xpath=//*[name()=\'button\' and @data-test-subj="superDatePickerCommonlyUsed_Last_1 hour"]'
KibanatimepickerLast24hours='xpath=//*[name()="button" and @data-test-subj="superDatePickerCommonlyUsed_Last_24 hours"]'
#KibanatimepickerLast24hours='//*[name()="button" and @data-test-subj="superDatePickerCommonlyUsed_Last_30 days"]'

Kibanasearch='xpath=//*[name()=\'textarea\' and @placeholder="Search"]'
Kibanarefreshbtn='xpath=//*[name()=\'button\' and @data-test-subj="querySubmitButton"]'
Kibanatableresult='xpath=//*[name()=\'div\' and @class="dscResults"]'


Kibanaglobalusrnamein='#username'
Kibanaglobalpasswrdin='#password'
Kibanaglobalsignin='#kc-login'
Kibanarefresh='#kibanaAppLocalApp_d3fdf0c6-607f-11eb-bdd6-37e899c3c31d > div > div > discover-app > kbn-top-nav > kbn-top-nav-helper > span > div.globalQueryBar > div.euiFlexGroup.euiFlexGroup--gutterSmall.euiFlexGroup--justifyContentFlexEnd.euiFlexGroup--directionRow.euiFlexGroup--responsive.kbnQueryBar.kbnQueryBar--withDatePicker > div.euiFlexItem.euiFlexItem--flexGrowZero > div > div.euiFlexItem.euiFlexItem--flexGrowZero > span > button'
Kibanabackenddropdown='//*[@id="discover-sidebar"]/div/discover-sidebar/section/div[1]/div/div/button/span/span'
Kibanabackendfilter='#kibana-app > div:nth-child(6) > div > div:nth-child(3) > div > div:nth-child(3) > div > div.euiSelectable > div.euiFormControlLayout.euiFormControlLayout--fullWidth.euiFormControlLayout--compressed > div > input'
Kibanaindextosearch='#ib1803fe0-5a39-11eb-9acd-03ab376ec5d0__option-0 > span > span > span > strong'
Kibanastarttime='#kibanaAppLocalApp_97615968-5a38-11eb-9acd-03ab376ec5d0 > div > div > discover-app > kbn-top-nav > kbn-top-nav-helper > span > div.globalQueryBar > div.euiFlexGroup.euiFlexGroup--gutterSmall.euiFlexGroup--justifyContentFlexEnd.euiFlexGroup--directionRow.euiFlexGroup--responsive.kbnQueryBar.kbnQueryBar--withDatePicker > div.euiFlexItem.euiFlexItem--flexGrowZero > div > div.euiFlexItem.kbnQueryBar__datePickerWrapper > div > div > div > div.euiFormControlLayout__childrenWrapper > div > div.euiPopover.euiPopover--anchorDownLeft.euiPopover--displayBlock.euiSuperDatePicker__startPopoverButton > div > button'
Kibanainputtime='#fsbk5yos'
Kibanatimeupdate='#kibanaAppLocalApp_97615968-5a38-11eb-9acd-03ab376ec5d0 > div > div > discover-app > kbn-top-nav > kbn-top-nav-helper > span > div.globalQueryBar > div.euiFlexGroup.euiFlexGroup--gutterSmall.euiFlexGroup--justifyContentFlexEnd.euiFlexGroup--directionRow.euiFlexGroup--responsive.kbnQueryBar.kbnQueryBar--withDatePicker > div.euiFlexItem.euiFlexItem--flexGrowZero > div > div.euiFlexItem.euiFlexItem--flexGrowZero > span > button'

Kibanatenantprivate='//*[name()="label" and @class="euiRadio__label" and @for="private"]'