eleGroupModel="xpath=//li//a[contains(@name,'Groups')]"
GroupModelPaginationEndCheck="xpath=//button[contains(@class,'p-paginator-next')]"
GroupModelTableRowText="//app-groups-model//tr[contains(.,'MODEL')]"
GroupModelTableHeaderText="//app-groups-model//table"
btnWifiOptimizationModelGroupSearch="//button[contains(.,'Search')]"
btnWifiOptimizationModelGroupNameDelete="css=app-groups-model pv-vector[name='circle_delete']"
toaster="#toast-container > div  > div"
selectModelProfileForGroupModelCreateClick="xpath=//p-dropdown[@formcontrolname='modelProfile']//span"
selectSupplyAndModelForGroupModelCreate="xpath=//p-multiselect[@formcontrolname='supplierModel']//div"
btnWifiOptimizationModelGroupNameEdit="xpath=//button//pv-vector[contains(@name,'edit')]"
btnWifiOptimizationProfileModelDelete="xpath=//pv-data-table[contains(.,'PROFILE')]//pv-vector[@name='circle_delete']"
